apiVersion: v1
kind: ReplicationController
metadata:
  name: scope-app
  labels:
    name: scope-app
spec:
  replicas: 1
  selector:
    name: scope-app
  template:
    metadata:
      labels:
        name: scope-app
    spec:
      containers:
      - name: scope-app
        image: weaveworks/scope
        command: ["/home/weave/entrypoint.sh", "--no-probe"]
        ports:
        - containerPort: 4040
